export const FILE_ACTION_TYPE = {
  GET_FILES_BY_USER_START: "file/GET_FILES_BY_USER_START",
  GET_FILES_BY_USER_SUCCESS: "file/GET_FILES_BY_USER_SUCCESS",
  GET_FILES_BY_USER_FAILED: "file/GET_FILES_BY_USER_FAILED",
  ADD_FILE_BY_USER_START: "file/ADD_FILE_BY_USER_START",
  ADD_FILE_BY_USER_SUCCESS: "file/ADD_FILE_BY_USER_SUCCESS",
  ADD_FILE_BY_USER_FAILED: "file/ADD_FILE_BY_USER_FAILED",
  DELETE_FILE_BY_USER_START: "file/DELETE_FILE_BY_USER_START",
  DELETE_FILE_BY_USER_SUCCESS: "file/DELETE_FILE_BY_USER_SUCCESS",
  DELETE_FILE_BY_USER_FAILED: "file/DELETE_FILE_BY_USER_FAILED",
};
